### ISSUE TITLE
COCO BBOX IDs

### ISSUE THREAD

**Issue by ttamyurek** [laclouis5/ObjectDetectionEval#2]
Brooo, your COCO label bbox id generation is not right. They're supposed to be unique numbers for each bbox.

**Comment by laclouis5** [comment]
Hi, if you want to contribute please be more specific when describing the issue. Could you precisely describe the issue, where and when it occurs? If you got wrong evaluation results you may want to provide the code and data you used so that I can reproduce the issue.

Also, if you want to contribute you can open a Pull Request in order to propose a bug fix or a new feature.
